## INF1608 - Análise Numérica - 2017.1
## Departamento de Informática - PUC-Rio 
## Prof. Hélio Lopes - lopes@inf.puc-rio.br
## http://www.inf.puc-rio.br/~lopes


# Exercícios resolvidos

R1) Faça uma função que verique se uma matriz A de tamanho nxn é estritamente diagonal dominante:
        Definição: Uma matriz A (nxn) é estritamente diagonal dominante se para toda linha i vale:
                   $$|A_{i,i}| > \sum_{i=1, i\ne j}^n |A_{i,j}|$$
                   
R2) Implemente o método de Jacobi para a solução de um sistema de equações lineares. Defina um critério de parada para o seu método, e explique-o. 
        https://pt.wikipedia.org/wiki/M%C3%A9todo_de_Jacobi

R3) Implemente o método de Gauss-Seidel para a solução de um sistema de equações lineares. Defina um critério de parada para o seu método, e explique-o.
        https://pt.wikipedia.org/wiki/M%C3%A9todo_de_Gauss-Seidel

## Lista 4

1) Implemente o método de Gradiente Conjugado para a solução de um sistema de equações lineares. Defina um critério de parada para o seu método, e explique-o.
        https://en.wikipedia.org/wiki/Conjugate_gradient_method

2) Teste muito bem todos esses algoritmos!

## Solução

R1) Faça uma função que verique se uma matriz A de tamanho nxn é estritamente diagonal dominante: 

Definição: Uma matriz A (nxn) é estritamente diagonal dominante se para toda linha i vale:
  $$|A_{i,i}| > \sum_{i=1, i\ne j}^n |A_{i,j}|$$
 


In [11]:
import numpy as np
import math

def isdiagonaldominat(A):
    n = len(A)
    for i in range(n):
        soma = 0.0
        for j in range(n):
            if (i != j):
                a = A[i,j]
                soma += math.fabs(a)
        if (math.fabs(A[i,i]) <= soma):
            return False
    return True

A = np.matrix([[-2.0,1.0,0.0],[1.0,-2.0,1.0],[0.0,1.0,-2.0]])
print(A)
print(isdiagonaldominat(A))


[[-2.  1.  0.]
 [ 1. -2.  1.]
 [ 0.  1. -2.]]
False


R2) Implemente o método de Jacobi para a solução de um sistema de equações lineares. Defina um critério de parada para o seu método, e explique-o. https://pt.wikipedia.org/wiki/M%C3%A9todo_de_Jacobi

In [16]:
import numpy as np

def jacobi(A,b,x0,N,TOL):

    nlin = len(A); #num. de linhas
    x = np.zeros(nlin); #cria x
   
    #iteracoes
    k = 1;
    while (k <= N):
        #iteracao de Jacobi
        for i in range(nlin):
            x[i] = 0.0;
            for j in range(i):
                x[i] = x[i] - A[i,j]*x0[j]
            for j in range(i+1,nlin):
                x[i] = x[i] - A[i,j]*x0[j]
            x[i] = (x[i] + b[i])/A[i,i]
        #criterio de parada
        if (np.linalg.norm(x-x0) < TOL):
            return x,k
        #prepara nova iteracao
        k = k+1;
        x0 = np.copy(x)
    return x0,k


A = np.matrix([[2.0,1.0],[5.0,7.0]])
b = np.array([11.0,13.0])
guess = np.array([1.0,1.0])

sol,n = jacobi(A,b,guess,100,0.000001)

print "A:"
print(A)

print "b:"
print(b)

print "x:"
print(sol)

print "||Ax-b||:"
print(np.linalg.norm(A.dot(sol)-b))

print "Numero de iteracoes:"
print(n)


A:
[[ 2.  1.]
 [ 5.  7.]]
b:
[ 11.  13.]
x:
[ 7.1111107  -3.22222137]
||Ax-b||:
3.92347242466e-06
Numero de iteracoes:
31


R3) Implemente o método de Gauss-Seidel para a solução de um sistema de equações lineares. Defina um critério de parada para o seu método, e explique-o. https://pt.wikipedia.org/wiki/M%C3%A9todo_de_Gauss-Seidel

In [19]:
import numpy as np

def gaussseidel(A,b,x0,N,TOL):

    nlin = len(A); #num. de linhas
    x = np.zeros(nlin); #cria x
   
    #iteracoes
    k = 1;
    while (k <= N):
        #iteracao de Jacobi
        for i in range(nlin):
            s = 0.0;
            for j in range(i):
                s = s + A[i,j]*x[j]
            for j in range(i+1,nlin):
                s = s + A[i,j]*x0[j]
            x[i] = (b[i] - s)/A[i,i]
        #criterio de parada
        if (np.linalg.norm(x-x0) < TOL):
            return x,k
        #prepara nova iteracao
        k = k+1;
        x0 = np.copy(x)
    return x0,k


A = np.matrix([[2.0,1.0],[5.0,7.0]])
b = np.array([11.0,13.0])
guess = np.array([1.0,1.0])

sol,n = gaussseidel(A,b,guess,100,0.000001)

print "A:"
print(A)

print "b:"
print(b)

print "x:"
print(sol)

print "||Ax-b||:"
print(np.linalg.norm(A.dot(sol)-b))

print "Numero de iteracoes:"
print(n)


A:
[[ 2.  1.]
 [ 5.  7.]]
b:
[ 11.  13.]
x:
[ 7.1111107  -3.22222193]
||Ax-b||:
5.3245767262e-07
Numero de iteracoes:
16


1) Implemente o método de Gradiente Conjugado para a solução de um sistema de equações lineares. Defina um critério de parada para o seu método, e explique-o. https://en.wikipedia.org/wiki/Conjugate_gradient_method
2) Teste muito bem todos esses algoritmos!

In [22]:
import numpy as np

def conjugateGradient(A,b,x0,N,TOL):
    n = len(A)
    x = np.zeros(n)
    k = 0
    r0 = np.copy(b - A.dot(x0))
    p = np.copy(r0)
    while(k < N):
        alpha = r0.dot(r0)/p.dot(A.dot(p))
        x = np.copy(x0 + alpha * p)
        r = np.copy(r0 - alpha * A.dot(p))
        if (np.linalg.norm(r) < TOL):
            return x, k
        p = np.copy(r + p * r.dot(r) / r0.dot(r0))
        # nova iteração
        k = k + 1
        x0 = np.copy(x)
        r0 = np.copy(r)
    return x0, k

# GERAR UMA MATRIZ SIMÉTRICA POSITIVA DEFINIDA DIAGONAL DOMINANTE PARA FINS DE TESTE

D = np.array([[13.,0.,0.,0.],[0.,2.,0.,0.],[0.,0.,5.,0.],[0.,0.,0.,11.]]) # Matriz diagal de autovalores positivos
P = np.array([[1.,1.,1.,1.],[1.,1.,-1.,-1.],[-1.,1.,-1.,1.],[1.,-1.,-1.,1.]]) # Matriz de colunas ortogonais
P = P/np.sqrt(4.)# Normalizar colunas para gerar matriz ortogonal
Pt = P.transpose()
Pinv = np.linalg.inv(P)
print ("Pt - Pinv: (Deve ser 0 para P ser ortogonal)\n" + str(Pt-Pinv)) # Teste se P é ortogonal
A = Pt.dot(D.dot(P))# A = P^(-1)DP

#A = np.array([[1577.0,3460.0,753.0],[3460.0,37052.0,4278.0],[753.0,4278.0,594.0]])
b = np.array([21.0,13.0,12.0,11.0])
chute = np.array([1.0,1.0,1.0,1.0])

#np.linalg.cholesky(A) # <- Só para garantir que a matriz é positiva definida

sol,n = conjugateGradient(A,b,chute,100,0.000001)

print "A: (Matriz gerada em bloco de código acima simérica, positiva definida)"
print(A)

print "b:"
print(b)

print "x:"
print(sol)

print "||Ax-b||:"
print(np.linalg.norm(A.dot(sol)-b))

print "Numero de iteracoes:"
print(n)

Pt - Pinv: (Deve ser 0 para P ser ortogonal)
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
A: (Matriz gerada em bloco de código acima simérica, positiva definida)
[[ 7.75 -0.25  1.25  4.25]
 [-0.25  7.75  4.25  1.25]
 [ 1.25  4.25  7.75 -0.25]
 [ 4.25  1.25 -0.25  7.75]]
b:
[ 21.  13.  12.  11.]
x:
[ 3.08024476  1.86206294  0.01206294 -0.56975524]
||Ax-b||:
0.0
Numero de iteracoes:
3


COMENTÁRIOS:
O método do gradiente conjugado só funciona para matrizes simétricas positivas definidas. Os critérios de parada que utilizei foram: limite K de iterações (preferencialmente k deve ser maior que n, a dimensão do vetor b), tolerância TOL máxima da norma do resto Ax-b (erro máximo tolerado). Note que na teoria, o número de iterações máximo deve ser a dimensão n do vetor b e o resultado exato. Numericamente, pelas aproximações, porém, isso não necessariamente é verdade.