## INF1608 - Análise Numérica - 2017.1
## Departamento de Informática - PUC-Rio 
## Prof. Hélio Lopes - lopes@inf.puc-rio.br
## http://www.inf.puc-rio.br/~lopes



## Lista 2

1) Modifique a implementação da decomposição LU para incluir a permutação de linhas, obtendo a decomposição PA=LU.

2) Implemente a função LUsolve que resolve o sistema Ax=b, tendo em mão a deomposição PA=LU.

3) Utilize as implementações dos items 1 e 2 da lista para resolver o sistema Ax = b, onde:

A = np.matrix([[1.,0.,0.,1.],[-1.,1.,0.,1.],[-1.,-1.,1.,1.],[-1.,-1.,-1.,1.]])
e
b = np.array([1.,1.,2.,0.])


In [13]:
import numpy as np

def LUdecomp(A):
    LU = np.copy(A)
    n  = len(A)
    sign=1.0
    p=range(n)
    for j in range(n-1):
        maxi=j
        c=abs(LU[j][j])
        for i in range(j+1,n):
            c1=abs(LU[i][j])
            if (c1>c):
                c=c1
                maxi=i
        if (j!=maxi):
            sign *=-1.0
            temp1=p[j]
            p[j]=p[maxi]
            p[maxi]=temp1
            for k in range(n):
                temp2=LU[maxi][k]
                LU[maxi][k]=LU[j][k]
                LU[j][k]=temp2
        for i in range(j+1,n):
            LU[i][j]=LU[i][j]/LU[j][j]
            for k in range(j+1,n):
                LU[i][k] = LU[i][k] - LU[i][j]*LU[j][k]
    return LU , p, sign

def LUforwardsub (L,p,b):
    n = len(L)
    y = np.zeros(n)
    y[0] = b[p[0]]
    for i in range(1,n):
        y[i] = b[p[i]]
        for j in range(i):
            y[i] = y[i] - L[i][j]*y[j]
    return y
            
def LUbackwardsub (U,y):
    n = len(U)
    x = np.zeros(n)
    x[n-1] = y[n-1]/U[n-1][n-1]
    for i in range(n-2,-1,-1):
        x[i] = y[i]
        for j in range(i+1,n):
            x[i] = x[i] - U[i][j]*x[j]
        x[i] /= U[i][i]
    return x
    
def LUsolve(LU,p,b):
    y = LUforwardsub(LU,p,b)
    x = LUbackwardsub(LU,y)
    return x
  
def LUgetL(LU):
    L  = np.copy(LU,p,b)
    n  = len(LU)
    for i in range(0,n):
        L[i,i] = 1.0
        for j in range(i+1,n):
            L[i][j] = 0.0
    return L
    
def LUgetU(LU):
    U  = np.copy(LU)
    n  = len(LU)
    for i in range(1,n):
        for j in range(0,i):
            U[i][j] = 0.0
    return U
    
def LUinverse(LU,p):
    n = len(LU)
    e = np.zeros(n)
    I = np.zeros((n,n))
    for j in range(n):
        e[j] = 1.0
        x = LUsolve(LU,p,e)
        for i in range(n):
            I[i][j] = x[i]
        e[j] = 0.0
    return I

def LUdet(LU,sign):
    n = len(LU)
    det = sign
    for i in range(n):
        det = det * LU[i][i]
    return det


A = np.matrix([[1.,0.,0.,1.],[-1.,1.,0.,1.],[-1.,-1.,1.,1.],[-1.,-1.,-1.,1.]]) 
b = np.array([1.,1.,2.,0.])

LU, mTrocas, sinal = LUdecomp(A)
print ("LUdecomp(A) = " + str(LU))
print ("Matriz de trocas apos LUdecomp = " + str(mTrocas))
print ("Sinal apos LUdecomp = " + str(sinal))

x = LUsolve(LU,mTrocas,b)
print("Ax = b => x = " + str(x))

IA= LUinverse(LU,p)
print ("IA = " + str(IA))
print ("A*IA = " + str(np.dot(A,IA)))
print ("det(LU) = " + str(LUdet(LU,sinal)))
print ("Teste se b = A.x = " + str(np.dot(A,x)))



LUdecomp(A) = [[ 1.  0.  0.  1.]
 [-1.  1.  0.  2.]
 [-1. -1.  1.  4.]
 [-1. -1. -1.  8.]]
Matriz de trocas apos LUdecomp = range(0, 4)
Sinal apos LUdecomp = 1.0
Ax = b => x = [ 0.  0.  1.  1.]
IA = [[ 0.5   -0.25  -0.125 -0.125]
 [ 0.     0.5   -0.25  -0.25 ]
 [ 0.     0.     0.5   -0.5  ]
 [ 0.5    0.25   0.125  0.125]]
A*IA = [[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
det(LU) = 8.0
Teste se b = A.x = [[ 1.  1.  2.  0.]]
