## INF1608 - Análise Numérica - 2017.1
## Departamento de Informática - PUC-Rio 
## Prof. Hélio Lopes - lopes@inf.puc-rio.br
## http://www.inf.puc-rio.br/~lopes



## Lista 1

1) Faça a implementação da decomposição Cholesky, cuja entrada é uma matriz simétrica A definida positiva de tamanho nxn.

2) Faça a implementação das funções CLforwardsub e da CLbackwardsub, cuja entrada é a matriz L da decomposição Cholesky de uma matriz A de tamanho nxn.

3) Implemente a função CLsolve que resolve o sistema Ax=b, tendo em mão a deomposição A=LLt.

4) Teste muito bem todos esses algoritmos!

In [88]:
import numpy as np
import numpy.linalg as alg

#1)
""" choleskyDecomp:
    Faz a decomposição cholesky de A e retorna a matriz L tal que A = LL^t.
    Assume que A é real simétrica definida positiva.
"""
def choleskyDecomp(A):
    n = len(A)
    L = np.copy(A)
    for j in range(n):
        for i in range(j):
            L[i][j] = 0
        sum1 = 0
        for k in range(j):
            sum1 += (L[j][k])**2
        L[j][j] = np.sqrt(A[j][j] - sum1)
        for i in range(j+1,n):
            sum2 = 0
            for k in range(j):
                sum2 += L[i][k]*L[j][k]
            L[i][j] = (A[i][j] - sum2) / L[j][j]
    return L

print ("Teste de choleskyDecomp:")
A = np.array([[10.,2.],[2.,4.]])
print ("A:\n" + str(A))
L = choleskyDecomp(A)
print ("L:\n" + str(L))
L2 = alg.cholesky(A)
print ("L2 (cholesky do linalg):\n" + str(L2))
print ("LL^t:\n" + str(L.dot(L.transpose())))

#2)
""" CLforwardsub:
    Recebe a matriz L da decomposição de cholesky e um vetor b 
    e resolve o sistema Ly = b por forward substitution, retornando y.
"""
def CLforwardsub(L, b):
    n = len(L)
    y = np.copy(b)
    for i in range(n):
        sum1 = 0
        for k in range(i):
            sum1 += y[k]*L[i][k]
        y[i] = (b[i] - sum1) / L[i][i]
    return y

""" CLbackwardsub:
    Recebe a matriz L da decomposição de cholesky e um vetor y resultado
    de um CLforwardsub e resolve o sistema L^tx = y por backward
    substitution, retornando y.
"""
def CLbackwardsub(L, y):
    n = len(L)
    x = np.copy(y)
    for i in range(n):
        i = n - i - 1
        sum1 = 0
        for k in range(i + 1, n):
            sum1 += x[k]*L[k][i]
        x[i] = (y[i] - sum1) / L[i][i]
    return x

print("\nTeste de forward/backward substitution:")
A = np.array([[1.,2.],[2.,13.]])
print ("A:\n" + str(B))
L = choleskyDecomp(B)
print ("L:\n" + str(L))
b = np.array([4.,5.])
print("b:\n" + str(b))
y = CLforwardsub(L,b)
print("Ly = b => y:\n" + str(y))
x = CLbackwardsub(L,y)
print("L^tx = y => x:\n" + str(x))

#3)
""" CLsolve:
    Recebe a matriz quadrada real simétrica definida positiva A e o vetor 
    b e resolve o sistema Ax = b por decomposição de Cholesky.
    Retorna a solução do sistema, o vetor x.
"""
def CLsolve(A, b):
    L = choleskyDecomp(A)
    y = CLforwardsub(L, b)
    x = CLbackwardsub(L, y)
    return x

print("\nTeste de solve:")
A = np.array([[10.,2.,1.],[2.,4.,2.],[1.,2.,3.]])
print ("A:\n" + str(A))
#np.linalg.cholesky(A) #<- Só para verificar se A é positiva definida
b = np.array([6.,7.,8.])
print("b:\n" + str(b))
x = CLsolve(A, b)
print("Ax = b => x:\n" + str(x))
x2 = alg.solve(A, b)
print("Ax = b => x: (solve do linalg)\n" + str(x2))

#4)
"""
    Algoritmos foram testados em suas questões respectivas, com o resultado
    comparado ao obtido à mão ou o resultado das funções similares implementadas
    pela biblioteca numpy.linalg. Todos os resultados foram satisfatórios e
    coincidiram com o esperado.
"""

Teste de choleskyDecomp:
A:
[[ 10.   2.]
 [  2.   4.]]
L:
[[ 3.16227766  0.        ]
 [ 0.63245553  1.8973666 ]]
L2 (cholesky do linalg):
[[ 3.16227766  0.        ]
 [ 0.63245553  1.8973666 ]]
LL^t:
[[ 10.   2.]
 [  2.   4.]]

Teste de forward/backward substitution:
A:
[[  1.   2.]
 [  2.  13.]]
L:
[[ 1.  0.]
 [ 2.  3.]]
b:
[ 4.  5.]
Ly = b => y:
[ 4. -1.]
L^tx = y => x:
[ 4.66666667 -0.33333333]

Teste de solve:
A:
[[ 10.   2.   1.]
 [  2.   4.   2.]
 [  1.   2.   3.]]
b:
[ 6.  7.  8.]
Ax = b => x:
[ 0.27777778  0.48611111  2.25      ]
Ax = b => x: (solve do linalg)
[ 0.27777778  0.48611111  2.25      ]
