PUC- Rio - Prova 2017.1 - INF1608 - Rafael Rubim Cabral (Matrícula - 1511068)

Questões 1), 2), 3)

In [3]:
import numpy as np
import math

#Questão 1)
def CholeskyDecompTridiag(A):
    L = np.copy(A)
    n = len(A)
    L[0][0] = L[0,0]
    for j in range(n):
        L[j][j] = L[j][j]
        if (j > 0):
            L[j][j] -= (L[j][j-1])**2
        L[j][j] = math.sqrt(L[j][j])
        if (j < n-1):
            L[j+1][j] /= L[j][j]
    for i in range(n-1):
        for j in range(i+1,n):
            L[i][j] = 0.0
    return L

#Questão 2)
# Código modificado pedido pela questão
def LforwardsubTridiag (L,b):
    n = len(L)
    y = np.zeros(n)
    y[0] = b[0]/L[0][0]
    for i in range(1,n):
        y[i] = b[i]
        y[i] = y[i] - L[i][i-1]*y[i-1]
        y[i] = y[i]/L[i][i]
    return y

# Código original mantido para testes
def Lforwardsub (L,b):
    n = len(L)
    y = np.zeros(n)
    y[0] = b[0]/L[0][0]
    for i in range(1,n):
        y[i] = b[i]
        for j in range(i):
            y[i] = y[i] - L[i][j]*y[j]
        y[i] = y[i]/L[i][i]
    return y

# Código modificado pedido pela questão
def LTbackwardsubTridiag (L,y):
    n = len(L)
    x = np.zeros(n)
    x[n-1] = y[n-1]/L[n-1][n-1]
    for i in range(n-2,-1,-1):
        x[i] = y[i]
        x[i] = x[i] - L[i+1][i]*x[i+1]
        x[i] /= L[i][i]
    return x

def LTbackwardsub (L,y):
    n = len(L)
    x = np.zeros(n)
    x[n-1] = y[n-1]/L[n-1][n-1]
    for i in range(n-2,-1,-1):
        x[i] = y[i]
        for j in range(i+1,n):
            x[i] = x[i] - L[j][i]*x[j]
        x[i] /= L[i][i]
    return x

#Questão 3)
A = np.matrix([[4.0,-1.0,0.0,0.0],[-1.0,4.0,-1.0,0.0],[0.0,-1.0,4.0,-1.0],[0.0,0.0,-1.0,4.0]])
L = CholeskyDecompTridiag(A)
print("A:\n" + str(A))
# (Teste realizado comparando resultado com função do numpy)
print("Cholesky Numpy(A):\n" + str(np.linalg.cholesky(A)))
print("Cholesky Tridiagonal(A):\n" + str(L))
b = np.array([1.0,0.0,0.0,1.0])
y = LforwardsubTridiag(L, b)
# (Teste realizado comparando resultado com função original, não modificada)
print("Ly = b => (Pela forward sub original) y:\n" + str(Lforwardsub(L, b)))
print("Ly = b => (Pela forward sub tridiagonal) y:\n" + str(y))
x = LTbackwardsubTridiag(L, y)
# (Teste realizado comparando resultado com função original, não modificada)
print("(L^t)x = y => (Pela backward sub original) x:\n" + str(LTbackwardsub(L, y)))
print("(L^t)x = y => (Pela backward sub tridiagonal) x:\n" + str(x))

A:
[[ 4. -1.  0.  0.]
 [-1.  4. -1.  0.]
 [ 0. -1.  4. -1.]
 [ 0.  0. -1.  4.]]
Cholesky Numpy(A):
[[ 2.          0.          0.          0.        ]
 [-0.5         1.93649167  0.          0.        ]
 [ 0.         -0.51639778  1.93218357  0.        ]
 [ 0.          0.         -0.51754917  1.93187548]]
Cholesky Tridiagonal(A):
[[ 2.          0.          0.          0.        ]
 [-0.5         1.93649167  0.          0.        ]
 [ 0.         -0.51639778  1.93218357  0.        ]
 [ 0.          0.         -0.51754917  1.93187548]]
Ly = b => (Pela forward sub original) y:
[ 0.5         0.12909944  0.03450328  0.52687513]
Ly = b => (Pela forward sub tridiagonal) y:
[ 0.5         0.12909944  0.03450328  0.52687513]
(L^t)x = y => (Pela backward sub original) x:
[ 0.27272727  0.09090909  0.09090909  0.27272727]
(L^t)x = y => (Pela backward sub tridiagonal) x:
[ 0.27272727  0.09090909  0.09090909  0.27272727]


Questões 4), 5)

In [4]:
import numpy as np

#Questão 4)
# Código modificado pedido pela questão
def gaussseidelTridiag(A,b,x0,N,TOL):

    nlin = len(A); #num. de linhas
    x = np.zeros(nlin); #cria x
   
    #iteracoes
    k = 1;
    while (k <= N):
        #iteracao de Gauss-Seidel (para caso tridiagonal)
        for i in range(nlin):
            s = 0.0;
            if (i > 0): #j = i-1
                s = s + A[i,i-1]*x[i-1]
            if (i < nlin-1): #j = i+1
                s = s + A[i,i+1]*x0[i+1]
            x[i] = (b[i] - s)/A[i,i]
        #criterio de parada
        if (np.linalg.norm(x-x0) < TOL):
            return x,k
        #prepara nova iteracao
        k = k+1;
        x0 = np.copy(x)
    return x0,k

# Código original mantido para testes
def gaussseidel(A,b,x0,N,TOL):

    nlin = len(A); #num. de linhas
    x = np.zeros(nlin); #cria x
   
    #iteracoes
    k = 1;
    while (k <= N):
        #iteracao de Gauss-Seidel
        for i in range(nlin):
            s = 0.0;
            for j in range(i):
                s = s + A[i,j]*x[j]
            for j in range(i+1,nlin):
                s = s + A[i,j]*x0[j]
            x[i] = (b[i] - s)/A[i,i]
        #criterio de parada
        if (np.linalg.norm(x-x0) < TOL):
            return x,k
        #prepara nova iteracao
        k = k+1;
        x0 = np.copy(x)
    return x0,k

#Questão 5)
A = np.matrix([[4.0,-1.0,0.0,0.0],[-1.0,4.0,-1.0,0.0],[0.0,-1.0,4.0,-1.0],[0.0,0.0,-1.0,4.0]])
b = np.array([1.0,0.0,0.0,1.0])
x0 = np.array([0.0,0.0,0.0,0.0])
N = 20
TOL = 0.000001
xOrig, itOrig = gaussseidel(A, b, x0, N, TOL)
xTridiag, itTridiag = gaussseidelTridiag(A, b, x0, N, TOL)
# (Teste realizado comparando resultado com função original, não modificada)
print("Ax = b => (Pelo Gauss-Seidel original, " + str(N) + " iteracoes maximas, tolerancia maxima " + str(TOL) + ") x:\n" + str(xOrig) + "\nIteracoes totais: " + str(itOrig))
print("Ax = b => (Pelo Gauss-Seidel original, " + str(N) + " iteracoes maximas, tolerancia maxima " + str(TOL) + ") x:\n" + str(xTridiag) + "\nIteracoes totais: " + str(itTridiag))

Ax = b => (Pelo Gauss-Seidel original, 20 iteracoes maximas, tolerancia maxima 1e-06) x:
[ 0.27272716  0.09090902  0.09090906  0.27272727]
Iteracoes totais: 9
Ax = b => (Pelo Gauss-Seidel original, 20 iteracoes maximas, tolerancia maxima 1e-06) x:
[ 0.27272716  0.09090902  0.09090906  0.27272727]
Iteracoes totais: 9


Questão 6)
    Aparentemente as duas soluções foram as mesmas, mas isso ocorreu porque a aproximação numérica foi tão boa que os resultados se aproximaram em menores precisões. O método iterativo (Gauss-Seidel), apesar de muitas vezes apresentar ganho computacional, não apresenta solução necessariamente correta, apenas uma aproximação muito dependente do chute inicial (x0), número de iterações máximo (N) e tolerância de erro máximo (TOL). No meu caso, usei uma tolerância baixíssima e o método convergiu bem rápido (9 iterações). Cholesky, por outro lado, apresenta solução analítica, que portanto é matemáticamente correta, apesar de poder apresentar custo computacional maior. Assim, Cholesky possui um erro menor (ou igual) independente dos parâmetros de Gauss-Seidel (x0, N, TOL), isso desconsiderando as aproximações discretas de ponto flutuante, claro. Para uma tolerância de Gauss-Seidel menor, pode-se deixar isso evidente no código abaixo:

In [5]:
import numpy as np

A = np.matrix([[4.0,-1.0,0.0,0.0],[-1.0,4.0,-1.0,0.0],[0.0,-1.0,4.0,-1.0],[0.0,0.0,-1.0,4.0]])
b = np.array([1.0,0.0,0.0,1.0])
x0 = np.array([0.0,0.0,0.0,0.0])

#Cholesky
L = CholeskyDecompTridiag(A)
y = LforwardsubTridiag(L, b)
xCholesky = LTbackwardsubTridiag(L, y)

#Gauss-Seidel
xGaussSeidel, it = gaussseidelTridiag(A, b, x0, 3, 0.1)

#Solução do numpy "analítica"
xNumpy = np.linalg.solve(A, b)

print("Erro do Cholesky: " + str(np.linalg.norm(xNumpy - xCholesky)))
print("Erro do Cholesky 2: " + str(np.linalg.norm(A.dot(xCholesky) - b)))
print("Erro do Gauss-Seidel: " + str(np.linalg.norm(xNumpy - xGaussSeidel)))

Erro do Cholesky: 0.0
Erro do Cholesky 2: 1.58231126132e-16
Erro do Gauss-Seidel: 0.0240383117269
